#!/bin/sh
set -e

# claudette installer
# Generated by godownloader

OWNER="montanaflynn"
REPO="claudette"
BINARY="claudette"
FORMAT="tar.gz"
BINDIR="/usr/local/bin"

usage() {
	echo "Usage: $0 [options]"
	echo
	echo "Options:"
	echo "  -b, --bindir BINDIR  Directory to install binary to (default: $BINDIR)"
	echo "  -d, --debug          Enable debug logging"
	echo "  -h, --help           Display this help message"
	echo "  -t, --tag TAG        Tag (version) to install (default: latest)"
}

log() {
	echo "[$BINARY] $1"
}

debug() {
	if [ "$DEBUG" = "1" ]; then
		echo "[$BINARY] [DEBUG] $1"
	fi
}

# Parse arguments
while [ $# -gt 0 ]; do
	case "$1" in
		-b|--bindir)
			BINDIR="$2"
			shift 2
			;;
		-d|--debug)
			DEBUG=1
			shift
			;;
		-h|--help)
			usage
			exit 0
			;;
		-t|--tag)
			TAG="$2"
			shift 2
			;;
		*)
			echo "Unknown argument: $1"
			usage
			exit 1
			;;
	esac
done

# Detect OS and Arch
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$ARCH" in
	x86_64|amd64) ARCH="x86_64" ;;
	arm64|aarch64) ARCH="arm64" ;;
	i386) ARCH="i386" ;;
	*)
		log "Unsupported architecture: $ARCH"
		exit 1
		;;
esac

case "$OS" in
	linux) ;;
	darwin) ;;
	*)
		log "Unsupported OS: $OS"
		exit 1
		;;
esac

# Determine tag
if [ -z "$TAG" ]; then
	TAG=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
	if [ -z "$TAG" ]; then
		log "Could not determine latest tag."
		exit 1
	fi
fi

debug "Detected OS: $OS"
debug "Detected Arch: $ARCH"
debug "Tag: $TAG"

# Construct download URL
# Naming convention: claudette_Darwin_x86_64.tar.gz
# We need to capitalize the first letter of OS for the filename match
OS_TITLE="$(echo "$OS" | sed 's/./\U&/')"
ASSET_NAME="${BINARY}_${OS_TITLE}_${ARCH}.${FORMAT}"
DOWNLOAD_URL="https://github.com/$OWNER/$REPO/releases/download/$TAG/$ASSET_NAME"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

log "Downloading $BINARY $TAG for $OS/$ARCH..."
debug "Downloading from $DOWNLOAD_URL"

if ! curl -sL "$DOWNLOAD_URL" -o "$TMP_DIR/$ASSET_NAME"; then
	log "Download failed."
	exit 1
fi

log "Installing to $BINDIR..."
mkdir -p "$TMP_DIR/extract"
tar -xzf "$TMP_DIR/$ASSET_NAME" -C "$TMP_DIR/extract"

if [ ! -w "$BINDIR" ]; then
	log "Sudo is required to install to $BINDIR"
	if ! sudo mv "$TMP_DIR/extract/$BINARY" "$BINDIR/$BINARY"; then
		log "Installation failed."
		exit 1
	fi
else
	mv "$TMP_DIR/extract/$BINARY" "$BINDIR/$BINARY"
fi

chmod +x "$BINDIR/$BINARY"
log "Successfully installed $BINARY to $BINDIR/$BINARY"
