# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudette < Formula
  desc "Claude Code usage statistics viewer"
  homepage "https://github.com/montanaflynn/claudette"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.5/claudette_Darwin_x86_64.tar.gz"
      sha256 "d41faa7ee471ac41cad9e895d1d0efe1f22bb3a439098d6652829d4cf9a8806d"

      def install
        bin.install "claudette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.5/claudette_Darwin_arm64.tar.gz"
      sha256 "2e9f59a29cc7b5aa5f9e358825f709d1604fc79ef244602faa28edf403e79bf5"

      def install
        bin.install "claudette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.5/claudette_Linux_x86_64.tar.gz"
      sha256 "50527d69d5168d0f6d0b8103ac0ab46ff474449bdc0db501d97a34474dd3193d"
      def install
        bin.install "claudette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.5/claudette_Linux_arm64.tar.gz"
      sha256 "1ebd1d7c4657721fd34773c90c4f2bcef00319dceed64a8195285c3cd14987d7"
      def install
        bin.install "claudette"
      end
    end
  end

  test do
    system "#{bin}/claudette --version"
  end
end
