# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudette < Formula
  desc "Claude Code usage statistics viewer"
  homepage "https://github.com/montanaflynn/claudette"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.0/claudette_Darwin_x86_64.tar.gz"
      sha256 "93c0e61aa15b26bae9cfb63ec7f3d6812371a8a4ea1f8f4a27f73f038584e7fe"

      def install
        bin.install "claudette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.0/claudette_Darwin_arm64.tar.gz"
      sha256 "24bf8f3ade2a4d93798349ef2ae35ddb149f4132dc89fc497f8a61012032df73"

      def install
        bin.install "claudette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.0/claudette_Linux_x86_64.tar.gz"
      sha256 "023c03de67fbffc197e915ea47922a083ee45342165e78fa2f6717546d2ca63e"
      def install
        bin.install "claudette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/montanaflynn/claudette/releases/download/v0.1.0/claudette_Linux_arm64.tar.gz"
      sha256 "22be50ab872b1ef870a67d0bda53bbd36a166dc1656b1ad3c701e2eb39f50f11"
      def install
        bin.install "claudette"
      end
    end
  end

  test do
    system "#{bin}/claudette --version"
  end
end
